"project_id_env": "CROWDIN_PROJECT_ID"
"api_token_env": "CROWDIN_PERSONAL_TOKEN"
"base_path": "."

"preserve_hierarchy": true

"files": [
  {
    "source": "src/generated/resources/assets/orge/lang/en_us.json",
    "translation": "src/main/resources/assets/orge/lang/%locale_with_underscore%.json",
    "languages_mapping": {
      "locale_with_underscore": {

      }
    }
  }
]