modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/RainBowCreation/ORGE/issues"

[[mixins]]
config = "orge.mixins.json"

[[mods]]
modId = "orge"
version = "${version}"
displayName = "ORGE"
authors = "RainBowCreation"
description = '''
Overhauled Realistic General Elements — per-block temperature & mass with native heat-conduction simulation.
'''

[[dependencies.orge]]
modId = "neoforge"
type = "required"
versionRange = "[21.11,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.orge]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.orge]]
modId = "architectury"
type = "required"
versionRange = "[19.0.0,)"
ordering = "AFTER"
side = "BOTH"
